//==================================================
// This file contains the excluded objects
// Generated by port connection exclusion engine
//==================================================
INSTANCE: tb_top.dut.U_REQ_ORDER.U_ADDR_BORDER_COUNT_RSP
Toggle addr[5]
Toggle len[5]
Toggle len_ext[5]
Toggle wrap_mask[5]
INSTANCE: tb_top.dut.U_REQ_ORDER
Toggle reqo2wd_timout_table[5]
INSTANCE: tb_top.dut.U_WATCHDOG
Toggle reqo2wd_timout_table[5]
INSTANCE: tb_top.dut
Toggle reqo2wd_timout_table[5]
