//==================================================
// This file contains the excluded objects
// Generated by port connection exclusion engine
//==================================================
INSTANCE: tb_top.dut.U_REQ_ORDER
Toggle opc[3]
Toggle rknp_xx2reqo_data[46]
INSTANCE: tb_top.dut.genblk1.U_WRAP_ALIGN
Toggle wa2reqo_data[46]
INSTANCE: tb_top.dut
Toggle rknp_xx2reqo_data[46]
