//==================================================
// This file contains the excluded objects
// Generated by port connection exclusion engine
//==================================================
INSTANCE: tb_top.dut.genblk1.U_WRAP_ADJUST
Toggle pending_offset[0]
