//==================================================
// This file contains the excluded objects
// Generated by port connection exclusion engine
//==================================================
INSTANCE: tb_top.dut.U_REQ_ORDER.U_ADDR_BORDER_COUNT_RSP
Toggle addr_begin[2:0]
INSTANCE: tb_top.dut.U_REQ_ORDER
Toggle rsp_addr_begin[2:0]
