//==================================================
// This file contains the excluded objects
// Generated by port connection exclusion engine
//==================================================
INSTANCE: tb_top.dut.U_WATCHDOG
Toggle rsp_timnot_tamp[15]
