//==================================================
// This file contains the excluded objects
// Generated by port connection exclusion engine
//==================================================
INSTANCE: tb_top.axi_vif
Toggle awsize
INSTANCE: tb_top.dut.U_WREQ_TRANS
Toggle axi_m_awsize[2:0]
INSTANCE: tb_top.dut
Toggle axi_m_awsize[2:0]
