//==================================================
// This file contains the excluded objects
// Generated by port connection exclusion engine
//==================================================
INSTANCE: tb_top.dut.U_WATCHDOG.U_SYNC_FIFO_TIMOUT
Toggle data_out[1]
INSTANCE: tb_top.dut.U_WATCHDOG
Toggle data_out[1]
Toggle wd2rspo_opc[1]
INSTANCE: tb_top.dut.genblk2.U_RSP_ORDER
Toggle wd2rspo_opc[1]
INSTANCE: tb_top.dut
Toggle wd2rspo_opc[1]
