//==================================================
// This file contains the excluded objects
// Generated by port connection exclusion engine
//==================================================
INSTANCE: tb_top.dut.genblk1.U_WRAP_ALIGN
Toggle 0to1 rknp_xx2wa_data[48]
INSTANCE: tb_top.dut
Toggle 0to1 rknp_rxreq_data[48]
