//==================================================
// This file contains the excluded objects
// Generated by port connection exclusion engine
//==================================================
INSTANCE: tb_top.dut.U_REQ_ORDER
Toggle reqo2rspo_rsp_offset_addr[0]
INSTANCE: tb_top.dut.genblk1.U_WRAP_ADJUST
Toggle rspo2wad_offset_addr[0]
INSTANCE: tb_top.dut.genblk2.U_RSP_ORDER
Toggle reqo2rspo_rsp_offset_addr[0]
Toggle rspo2wad_offset_addr[0]
INSTANCE: tb_top.dut
Toggle reqo2rspo_rsp_offset_addr[0]
Toggle rspo2wad_offset_addr[0]
