//==================================================
// This file contains the excluded objects
// Generated by port connection exclusion engine
//==================================================
INSTANCE: tb_top.dut.U_REQ_ORDER
Toggle rspo2reqo_head_index[4]
INSTANCE: tb_top.dut.genblk2.U_RSP_ORDER
Toggle rspo2reqo_head_index[4]
INSTANCE: tb_top.dut
Toggle rspo2reqo_head_index[4]
