//==================================================
// This file contains the excluded objects
// Generated by port connection exclusion engine
//==================================================
INSTANCE: tb_top.dut.genblk1.U_WRAP_ADJUST
Toggle wad2rknp_xx_data[36]
INSTANCE: tb_top.dut
Toggle rknp_txrsp_data[36]
