//==================================================
// This file contains the excluded objects
// Generated by port connection exclusion engine
//==================================================
INSTANCE: tb_top.dut.U_ADDR_MAP
Toggle am2rreqt_opc[1]
Toggle am2wreqt_opc[1]
Toggle rspo2am_opc[1]
INSTANCE: tb_top.dut.U_REQ_ORDER
Toggle reqo2rspo_opc[1]
INSTANCE: tb_top.dut.U_RREQ_TRANS
Toggle am2rreqt_opc[1]
INSTANCE: tb_top.dut.U_WREQ_TRANS
Toggle am2wreqt_opc[1]
INSTANCE: tb_top.dut
Toggle am2rreqt_opc[1]
Toggle am2wreqt_opc[1]
INSTANCE: tb_top.dut.genblk2.U_ELY_RSP_DETECT
Toggle rspo2erd_opc[1]
INSTANCE: tb_top.dut.genblk2.U_RSP_ORDER
Toggle reqo2rspo_opc[1]
Toggle rspo2am_opc[1]
Toggle rspo2erd_opc[1]
INSTANCE: tb_top.dut
Toggle reqo2rspo_opc[1]
Toggle rspo2am_opc[1]
