//==================================================
// This file contains the excluded objects
// Generated by port connection exclusion engine
//==================================================
INSTANCE: tb_top.dut.U_REQ_ORDER
Toggle wa2reqo_offset_addr[0]
INSTANCE: tb_top.dut.genblk1.U_WRAP_ALIGN
Toggle wa2reqo_offset_addr[0]
INSTANCE: tb_top.dut
Toggle wa2reqo_offset_addr[0]
