//==================================================
// This file contains the excluded objects
// Generated by port connection exclusion engine
//==================================================
INSTANCE: tb_top.dut.genblk2.U_ELY_RSP_DETECT
ANNOTATION: "rknp_xx2wa_head_d can only be asserted after accepting an
unaligned WRW request. Therefore head_d implies opc==WRW and
wa2reqo_offset_addr!=0. Combinations 0/1/1 and 1/0/1 are unreachable"
Toggle erd2rspo_status[1]
ANNOTATION: "rknp_xx2wa_head_d can only be asserted after accepting an
unaligned WRW request. Therefore head_d implies opc==WRW and
wa2reqo_offset_addr!=0. Combinations 0/1/1 and 1/0/1 are unreachable"
Toggle rspt2erd_status[1]
INSTANCE: tb_top.dut.genblk2.U_RSP_ORDER
ANNOTATION: "rknp_xx2wa_head_d can only be asserted after accepting an
unaligned WRW request. Therefore head_d implies opc==WRW and
wa2reqo_offset_addr!=0. Combinations 0/1/1 and 1/0/1 are unreachable"
Toggle rspt2rspo_status[1]
INSTANCE: tb_top.dut.genblk2.U_RSP_TRANS
ANNOTATION: "rknp_xx2wa_head_d can only be asserted after accepting an
unaligned WRW request. Therefore head_d implies opc==WRW and
wa2reqo_offset_addr!=0. Combinations 0/1/1 and 1/0/1 are unreachable"
Toggle rspt2rspo_status[1]
INSTANCE: tb_top.dut
ANNOTATION: "rknp_xx2wa_head_d can only be asserted after accepting an
unaligned WRW request. Therefore head_d implies opc==WRW and
wa2reqo_offset_addr!=0. Combinations 0/1/1 and 1/0/1 are unreachable"
Toggle rspt2rspo_status[1]
