//==================================================
// This file contains the excluded objects
// Generated by port connection exclusion engine
//==================================================
INSTANCE: tb_top.dut.U_WATCHDOG.U_SYNC_FIFO_TIMOUT
Toggle data_in[1]
INSTANCE: tb_top.dut.U_WATCHDOG
Toggle data_in[1]
