//==================================================
// This file contains the excluded objects
// Generated by port connection exclusion engine
//==================================================
INSTANCE: tb_top.dut.U_ADDR_MAP
Toggle am2rreqt_arlen[7:6]
Toggle am2wreqt_awlen[7:6]
Toggle beat_count[7:6]
Toggle total_flit[7:6]
INSTANCE: tb_top.dut.U_RREQ_TRANS
Toggle am2rreqt_arlen[7:6]
Toggle axi_m_arlen[7:6]
INSTANCE: tb_top.dut.U_WREQ_TRANS
Toggle am2wreqt_awlen[7:6]
Toggle axi_m_awlen[7:6]
INSTANCE: tb_top.dut
Toggle am2rreqt_arlen[7:6]
Toggle am2wreqt_awlen[7:6]
Toggle axi_m_arlen[7:6]
Toggle axi_m_awlen[7:6]
