//==================================================
// This file contains the excluded objects
// Generated by port connection exclusion engine
//==================================================
INSTANCE: tb_top.axi_vif
ANNOTATION: "rknp_xx2wa_head_d can only be asserted after accepting an
unaligned WRW request. Therefore head_d implies opc==WRW and
wa2reqo_offset_addr!=0. Combinations 0/1/1 and 1/0/1 are unreachable"
Toggle arsize
INSTANCE: tb_top.dut.U_RREQ_TRANS
ANNOTATION: "rknp_xx2wa_head_d can only be asserted after accepting an
unaligned WRW request. Therefore head_d implies opc==WRW and
wa2reqo_offset_addr!=0. Combinations 0/1/1 and 1/0/1 are unreachable"
Toggle axi_m_arsize[2:0]
INSTANCE: tb_top.dut
ANNOTATION: "rknp_xx2wa_head_d can only be asserted after accepting an
unaligned WRW request. Therefore head_d implies opc==WRW and
wa2reqo_offset_addr!=0. Combinations 0/1/1 and 1/0/1 are unreachable"
Toggle axi_m_arsize[2:0]
