//==================================================
// This file contains the excluded objects
// Generated by port connection exclusion engine
//==================================================
INSTANCE: tb_top.dut.genblk1.U_WRAP_ALIGN
Toggle opc[1]
Toggle rknp_xx2wa_data[44]
INSTANCE: tb_top.dut
Toggle rknp_rxreq_data[44]
