//==================================================
// This file contains the excluded objects
// Generated by port connection exclusion engine
//==================================================
INSTANCE: tb_top.dut.U_ADDR_MAP
Toggle rspo2am_subr[7:3]
INSTANCE: tb_top.dut.U_REQ_ORDER
Toggle reqo2rspo_subr[7:3]
INSTANCE: tb_top.dut.genblk2.U_RSP_ORDER
Toggle reqo2rspo_subr[7:3]
Toggle rspo2am_subr[7:3]
INSTANCE: tb_top.dut
Toggle reqo2rspo_subr[7:3]
Toggle rspo2am_subr[7:3]
