//==================================================
// This file contains the excluded objects
// Generated by port connection exclusion engine
//==================================================
INSTANCE: tb_top.dut.U_REQ_ORDER
Toggle reqo2wd_timout_table[25]
INSTANCE: tb_top.dut.U_WATCHDOG
Toggle reqo2wd_timout_table[25]
INSTANCE: tb_top.dut
Toggle reqo2wd_timout_table[25]
