//==================================================
// This file contains the excluded objects
// Generated by port connection exclusion engine
//==================================================
INSTANCE: tb_top.dut.U_REQ_ORDER.genblk24.U_ADDR_BORDER_COUNT_REQ
Toggle burst[1]
INSTANCE: tb_top.dut.U_REQ_ORDER
Toggle opc[1]
Toggle rknp_xx2reqo_data[44]
INSTANCE: tb_top.dut.genblk1.U_WRAP_ALIGN
Toggle wa2reqo_data[44]
INSTANCE: tb_top.dut
Toggle rknp_xx2reqo_data[44]
