//==================================================
// This file contains the Excluded objects
// Generated By User: ICer
// Format Version: 2
// Date: Sat Aug 15 15:21:01 2026
// ExclMode: default
//==================================================
CHECKSUM: "3438056735 3107786841"
INSTANCE: tb_top.dut.genblk2.U_RSP_TRANS
ANNOTATION_BEGIN: "rknp_xx2wa_head_d can only be asserted after accepting an
unaligned WRW request. Therefore head_d implies opc==WRW and
wa2reqo_offset_addr!=0. Combinations 0/1/1 and 1/0/1 are unreachable"
Toggle rspt2rspo_opc [1] "net rspt2rspo_opc[1:0]"
Toggle rspt2rspo_errcode "reg rspt2rspo_errcode[2:0]"
Toggle rspt2rspo_status [1] "reg rspt2rspo_status[1:0]"
Toggle rspt2rspo_data [0] "net rspt2rspo_data[72:0]"
ANNOTATION_END
CHECKSUM: "136218573 4266180489"
INSTANCE: tb_top.rknp_vif
ANNOTATION_BEGIN: "rknp_xx2wa_head_d can only be asserted after accepting an
unaligned WRW request. Therefore head_d implies opc==WRW and
wa2reqo_offset_addr!=0. Combinations 0/1/1 and 1/0/1 are unreachable"
Toggle rxreq_data [34:30] "logic rxreq_data[174:0]"
Toggle rxreq_data [44] "logic rxreq_data[174:0]"
Toggle rxreq_data [46] "logic rxreq_data[174:0]"
Toggle rxreq_data [48] "logic rxreq_data[174:0]"
Toggle txrsp_data [36] "logic txrsp_data[156:0]"
ANNOTATION_END
CHECKSUM: "813889977 1161516725"
INSTANCE: tb_top.dut
Toggle rknp_rxreq_data [34:30] "net rknp_rxreq_data[174:0]"
Toggle rknp_rxreq_data [44] "net rknp_rxreq_data[174:0]"
Toggle rknp_rxreq_data [46] "net rknp_rxreq_data[174:0]"
Toggle rknp_rxreq_data [48] "net rknp_rxreq_data[174:0]"
Toggle rknp_txrsp_data [36] "net rknp_txrsp_data[156:0]"
Toggle rknp_xx2reqo_data [34:30] "net rknp_xx2reqo_data[174:0]"
Toggle rknp_xx2reqo_data [44] "net rknp_xx2reqo_data[174:0]"
Toggle rknp_xx2reqo_data [46] "net rknp_xx2reqo_data[174:0]"
Toggle rknp_xx2reqo_data [48] "net rknp_xx2reqo_data[174:0]"
Toggle reqo2rspo_subr [7:3] "net reqo2rspo_subr[7:0]"
Toggle reqo2rspo_opc [1] "net reqo2rspo_opc[3:0]"
Toggle reqo2rspo_opc [3] "net reqo2rspo_opc[3:0]"
Toggle reqo2rspo_status [1] "net reqo2rspo_status[1:0]"
Toggle reqo2rspo_tag_name [2] "net reqo2rspo_tag_name[55:0]"
Toggle reqo2rspo_tag_name [9] "net reqo2rspo_tag_name[55:0]"
Toggle reqo2rspo_tag_name [16] "net reqo2rspo_tag_name[55:0]"
Toggle reqo2rspo_tag_name [23] "net reqo2rspo_tag_name[55:0]"
Toggle reqo2rspo_tag_name [30] "net reqo2rspo_tag_name[55:0]"
Toggle reqo2rspo_tag_name [37] "net reqo2rspo_tag_name[55:0]"
Toggle reqo2rspo_tag_name [44] "net reqo2rspo_tag_name[55:0]"
Toggle reqo2rspo_tag_name [51] "net reqo2rspo_tag_name[55:0]"
Toggle wa2reqo_offset_addr [0] "net wa2reqo_offset_addr[7:0]"
Toggle wa2reqo_offset_addr [7:3] "net wa2reqo_offset_addr[7:0]"
Toggle reqo2rspo_rsp_offset_addr [0] "net reqo2rspo_rsp_offset_addr[7:0]"
Toggle reqo2rspo_rsp_offset_addr [7:3] "net reqo2rspo_rsp_offset_addr[7:0]"
Toggle rspo2reqo_head_index [4] "net rspo2reqo_head_index[8:0]"
Toggle reqo2wd_opc [1] "net reqo2wd_opc[1:0]"
Toggle reqo2wd_timout_table [5] "net reqo2wd_timout_table[79:0]"
Toggle reqo2wd_timout_table [15] "net reqo2wd_timout_table[79:0]"
Toggle reqo2wd_timout_table [25] "net reqo2wd_timout_table[79:0]"
Toggle reqo2wd_timout_table [35] "net reqo2wd_timout_table[79:0]"
Toggle reqo2wd_timout_table [45] "net reqo2wd_timout_table[79:0]"
Toggle reqo2wd_timout_table [55] "net reqo2wd_timout_table[79:0]"
Toggle reqo2wd_timout_table [65] "net reqo2wd_timout_table[79:0]"
Toggle reqo2wd_timout_table [75] "net reqo2wd_timout_table[79:0]"
Toggle rspo2wad_offset_addr [0] "net rspo2wad_offset_addr[7:0]"
Toggle rspo2wad_offset_addr [7:3] "net rspo2wad_offset_addr[7:0]"
Toggle rspo2am_subr [7:3] "net rspo2am_subr[7:0]"
Toggle rspo2am_opc [1] "net rspo2am_opc[3:0]"
Toggle rspo2am_opc [3] "net rspo2am_opc[3:0]"
Toggle am2rreqt_opc [1] "net am2rreqt_opc[1:0]"
Toggle am2wreqt_opc [1] "net am2wreqt_opc[1:0]"
ANNOTATION_BEGIN: "rknp_xx2wa_head_d can only be asserted after accepting an
unaligned WRW request. Therefore head_d implies opc==WRW and
wa2reqo_offset_addr!=0. Combinations 0/1/1 and 1/0/1 are unreachable"
Toggle axi_m_awaddr [34:32] "net axi_m_awaddr[39:0]"
Toggle axi_m_awaddr [39] "net axi_m_awaddr[39:0]"
Toggle axi_m_awlen [7:6] "net axi_m_awlen[7:0]"
Toggle axi_m_araddr [34:32] "reg axi_m_araddr[39:0]"
Toggle axi_m_araddr [39] "reg axi_m_araddr[39:0]"
Toggle axi_m_arlen [7:6] "reg axi_m_arlen[7:0]"
Toggle axi_m_arsize "reg axi_m_arsize[2:0]"
Toggle reqo2wd_timout_table [1] "net reqo2wd_timout_table[79:0]"
Toggle rspt2rspo_opc [1] "net rspt2rspo_opc[1:0]"
Toggle rspt2rspo_errcode "net rspt2rspo_errcode[2:0]"
Toggle rspt2rspo_status [1] "net rspt2rspo_status[1:0]"
Toggle rspt2rspo_data [0] "net rspt2rspo_data[72:0]"
Toggle rspo2rknp_xx_data [36] "net rspo2rknp_xx_data[156:0]"
Toggle rspo2wd_opc [1] "net rspo2wd_opc[1:0]"
Toggle am2rreqt_araddr [34:32] "net am2rreqt_araddr[39:0]"
Toggle am2rreqt_araddr [39] "net am2rreqt_araddr[39:0]"
Toggle am2rreqt_arlen [7:6] "net am2rreqt_arlen[7:0]"
Toggle am2wreqt_awaddr [34:32] "net am2wreqt_awaddr[39:0]"
Toggle am2wreqt_awaddr [39] "net am2wreqt_awaddr[39:0]"
Toggle am2wreqt_awlen [7:6] "net am2wreqt_awlen[7:0]"
Toggle genblk2.rspt2erd_errcode "net genblk2.rspt2erd_errcode[2:0]"
Toggle genblk2.erd2rspo_errcode "net genblk2.erd2rspo_errcode[2:0]"
ANNOTATION_END
CHECKSUM: "1490924670 1371830841"
INSTANCE: tb_top.dut.genblk1.U_WRAP_ALIGN
Toggle rknp_xx2wa_data [34:30] "net rknp_xx2wa_data[174:0]"
Toggle rknp_xx2wa_data [44] "net rknp_xx2wa_data[174:0]"
Toggle rknp_xx2wa_data [46] "net rknp_xx2wa_data[174:0]"
Toggle rknp_xx2wa_data [48] "net rknp_xx2wa_data[174:0]"
Toggle wa2reqo_data [34:30] "reg wa2reqo_data[174:0]"
Toggle wa2reqo_data [44] "reg wa2reqo_data[174:0]"
Toggle wa2reqo_data [46] "reg wa2reqo_data[174:0]"
Toggle wa2reqo_data [48] "reg wa2reqo_data[174:0]"
Toggle wa2reqo_offset_addr [0] "net wa2reqo_offset_addr[7:0]"
Toggle wa2reqo_offset_addr [7:3] "net wa2reqo_offset_addr[7:0]"
Toggle opc [1] "net opc[3:0]"
Toggle opc [3] "net opc[3:0]"
Toggle jud_addr [2:0] "net jud_addr[31:0]"
Toggle align_addr [2:0] "reg align_addr[31:0]"
Toggle offset_addr [7:3] "reg offset_addr[7:0]"
Toggle wwrap_buffer [34:30] "reg wwrap_buffer[174:0]"
Toggle wwrap_buffer [44] "reg wwrap_buffer[174:0]"
Toggle wwrap_buffer [46] "reg wwrap_buffer[174:0]"
Toggle wwrap_buffer [48] "reg wwrap_buffer[174:0]"
Toggle wwrap_buffer [59:57] "reg wwrap_buffer[174:0]"
Toggle offset_body [9:6] "net offset_body[9:0]"
CHECKSUM: "1490924670 1797030245"
INSTANCE: tb_top.dut.genblk1.U_WRAP_ALIGN
ANNOTATION_BEGIN: "rknp_xx2wa_head_d can only be asserted after accepting an
unaligned WRW request. Therefore head_d implies opc==WRW and
wa2reqo_offset_addr!=0. Combinations 0/1/1 and 1/0/1 are unreachable"
Condition 4 "971252251" "((opc == WRW) && (wa2reqo_offset_addr != 8'b0) && (rknp_xx2wa_head_d == 1'b1)) 1 -1" (1 "011")
Condition 4 "971252251" "((opc == WRW) && (wa2reqo_offset_addr != 8'b0) && (rknp_xx2wa_head_d == 1'b1)) 1 -1" (2 "101")
Condition 8 "3094471809" "((opc == WRW) && (offset_addr != 8'b0) && (rknp_xx2wa_head_d == 1'b1)) 1 -1" (1 "011")
Condition 8 "3094471809" "((opc == WRW) && (offset_addr != 8'b0) && (rknp_xx2wa_head_d == 1'b1)) 1 -1" (2 "101")
Condition 14 "1536077264" "(rknp_xx2wa_valid && rknp_xx2wa_head && (opc == RDW) && (wa2reqo_offset_addr != 8'b0)) 1 -1" (1 "0111")
Condition 14 "1536077264" "(rknp_xx2wa_valid && rknp_xx2wa_head && (opc == RDW) && (wa2reqo_offset_addr != 8'b0)) 1 -1" (2 "1011")
ANNOTATION_END
CHECKSUM: "3196658385 2343684093"
INSTANCE: tb_top.dut.U_REQ_ORDER.U_ADDR_BORDER_COUNT_RSP
Toggle addr [5] "net addr[31:0]"
Toggle len [5] "net len[7:0]"
Toggle addr_begin [2:0] "reg addr_begin[31:0]"
Toggle wrap_mask [5] "reg wrap_mask[31:0]"
Toggle len_ext [5] "reg len_ext[32:0]"
ANNOTATION_BEGIN: "rknp_xx2wa_head_d can only be asserted after accepting an
unaligned WRW request. Therefore head_d implies opc==WRW and
wa2reqo_offset_addr!=0. Combinations 0/1/1 and 1/0/1 are unreachable"
Toggle burst [1] "net burst[1:0]"
Toggle addr [1] "net addr[31:0]"
Toggle len [1] "net len[7:0]"
Toggle incr_first_addr "reg incr_first_addr[31:0]"
Toggle incr_first_addr [2:0] "reg incr_first_addr[31:0]"
Toggle wrap_mask [1] "reg wrap_mask[31:0]"
Toggle wrap_mask [31:8] "reg wrap_mask[31:0]"
Toggle first_byte_addr [2:0] "reg first_byte_addr[32:0]"
Toggle first_byte_addr [32] "reg first_byte_addr[32:0]"
Toggle last_byte_addr [32] "reg last_byte_addr[32:0]"
Toggle len_ext [1] "reg len_ext[32:0]"
Toggle len_ext [32:8] "reg len_ext[32:0]"
ANNOTATION_END
CHECKSUM: "3196658385 2306399019"
INSTANCE: tb_top.dut.U_REQ_ORDER.genblk24.U_ADDR_BORDER_COUNT_REQ
Toggle burst [1] "net burst[1:0]"
ANNOTATION_BEGIN: "rknp_xx2wa_head_d can only be asserted after accepting an
unaligned WRW request. Therefore head_d implies opc==WRW and
wa2reqo_offset_addr!=0. Combinations 0/1/1 and 1/0/1 are unreachable"
Toggle wrap_mask [31:8] "reg wrap_mask[31:0]"
Toggle first_byte_addr [32] "reg first_byte_addr[32:0]"
Toggle last_byte_addr [32] "reg last_byte_addr[32:0]"
Toggle len_ext [32:8] "reg len_ext[32:0]"
ANNOTATION_END
CHECKSUM: "3430638988 3921092857"
INSTANCE: tb_top.dut.U_REQ_ORDER
Toggle rknp_xx2reqo_data [34:30] "net rknp_xx2reqo_data[174:0]"
Toggle rknp_xx2reqo_data [44] "net rknp_xx2reqo_data[174:0]"
Toggle rknp_xx2reqo_data [46] "net rknp_xx2reqo_data[174:0]"
Toggle rknp_xx2reqo_data [48] "net rknp_xx2reqo_data[174:0]"
Toggle reqo2rspo_subr [7:3] "reg reqo2rspo_subr[7:0]"
Toggle reqo2rspo_opc [1] "reg reqo2rspo_opc[3:0]"
Toggle reqo2rspo_opc [3] "reg reqo2rspo_opc[3:0]"
Toggle reqo2rspo_status [1] "reg reqo2rspo_status[1:0]"
Toggle reqo2rspo_tag_name [2] "net reqo2rspo_tag_name[55:0]"
Toggle reqo2rspo_tag_name [9] "net reqo2rspo_tag_name[55:0]"
Toggle reqo2rspo_tag_name [16] "net reqo2rspo_tag_name[55:0]"
Toggle reqo2rspo_tag_name [23] "net reqo2rspo_tag_name[55:0]"
Toggle reqo2rspo_tag_name [30] "net reqo2rspo_tag_name[55:0]"
Toggle reqo2rspo_tag_name [37] "net reqo2rspo_tag_name[55:0]"
Toggle reqo2rspo_tag_name [44] "net reqo2rspo_tag_name[55:0]"
Toggle reqo2rspo_tag_name [51] "net reqo2rspo_tag_name[55:0]"
Toggle wa2reqo_offset_addr [0] "net wa2reqo_offset_addr[7:0]"
Toggle wa2reqo_offset_addr [7:3] "net wa2reqo_offset_addr[7:0]"
Toggle reqo2rspo_rsp_offset_addr [0] "reg reqo2rspo_rsp_offset_addr[7:0]"
Toggle reqo2rspo_rsp_offset_addr [7:3] "reg reqo2rspo_rsp_offset_addr[7:0]"
Toggle rspo2reqo_head_index [4] "net rspo2reqo_head_index[8:0]"
Toggle reqo2wd_opc [1] "reg reqo2wd_opc[1:0]"
Toggle reqo2wd_timout_table [5] "net reqo2wd_timout_table[79:0]"
Toggle reqo2wd_timout_table [15] "net reqo2wd_timout_table[79:0]"
Toggle reqo2wd_timout_table [25] "net reqo2wd_timout_table[79:0]"
Toggle reqo2wd_timout_table [35] "net reqo2wd_timout_table[79:0]"
Toggle reqo2wd_timout_table [45] "net reqo2wd_timout_table[79:0]"
Toggle reqo2wd_timout_table [55] "net reqo2wd_timout_table[79:0]"
Toggle reqo2wd_timout_table [65] "net reqo2wd_timout_table[79:0]"
Toggle reqo2wd_timout_table [75] "net reqo2wd_timout_table[79:0]"
Toggle subr [7:3] "net subr[7:0]"
Toggle opc [1] "net opc[3:0]"
Toggle opc [3] "net opc[3:0]"
Toggle status [1] "net status[1:0]"
Toggle rsp_addr_begin [2:0] "net rsp_addr_begin[31:0]"
ANNOTATION: "rknp_xx2wa_head_d can only be asserted after accepting an
unaligned WRW request. Therefore head_d implies opc==WRW and
wa2reqo_offset_addr!=0. Combinations 0/1/1 and 1/0/1 are unreachable"
Toggle reqo2wd_timout_table [1] "net reqo2wd_timout_table[79:0]"
CHECKSUM: "3554841995 1363517398"
INSTANCE: tb_top.dut.genblk2.U_RSP_ORDER
Toggle reqo2rspo_subr [7:3] "net reqo2rspo_subr[7:0]"
Toggle reqo2rspo_opc [1] "net reqo2rspo_opc[3:0]"
Toggle reqo2rspo_opc [3] "net reqo2rspo_opc[3:0]"
Toggle reqo2rspo_status [1] "net reqo2rspo_status[1:0]"
Toggle reqo2rspo_tag_name [2] "net reqo2rspo_tag_name[55:0]"
Toggle reqo2rspo_tag_name [9] "net reqo2rspo_tag_name[55:0]"
Toggle reqo2rspo_tag_name [16] "net reqo2rspo_tag_name[55:0]"
Toggle reqo2rspo_tag_name [23] "net reqo2rspo_tag_name[55:0]"
Toggle reqo2rspo_tag_name [30] "net reqo2rspo_tag_name[55:0]"
Toggle reqo2rspo_tag_name [37] "net reqo2rspo_tag_name[55:0]"
Toggle reqo2rspo_tag_name [44] "net reqo2rspo_tag_name[55:0]"
Toggle reqo2rspo_tag_name [51] "net reqo2rspo_tag_name[55:0]"
Toggle rspo2am_subr [7:3] "net rspo2am_subr[7:0]"
Toggle rspo2am_opc [1] "net rspo2am_opc[3:0]"
Toggle rspo2am_opc [3] "net rspo2am_opc[3:0]"
Toggle reqo2rspo_rsp_offset_addr [0] "net reqo2rspo_rsp_offset_addr[7:0]"
Toggle reqo2rspo_rsp_offset_addr [7:3] "net reqo2rspo_rsp_offset_addr[7:0]"
Toggle rspo2reqo_head_index [4] "reg rspo2reqo_head_index[8:0]"
Toggle rspo2wad_offset_addr [0] "net rspo2wad_offset_addr[7:0]"
Toggle rspo2wad_offset_addr [7:3] "net rspo2wad_offset_addr[7:0]"
Toggle rspo2erd_opc [1] "net rspo2erd_opc[3:0]"
Toggle rspo2erd_opc [3] "net rspo2erd_opc[3:0]"
ANNOTATION_BEGIN: "rknp_xx2wa_head_d can only be asserted after accepting an
unaligned WRW request. Therefore head_d implies opc==WRW and
wa2reqo_offset_addr!=0. Combinations 0/1/1 and 1/0/1 are unreachable"
Toggle rspt2rspo_opc [1] "net rspt2rspo_opc[1:0]"
Toggle rspt2rspo_errcode "net rspt2rspo_errcode[2:0]"
Toggle rspt2rspo_status [1] "net rspt2rspo_status[1:0]"
Toggle rspt2rspo_data [0] "net rspt2rspo_data[72:0]"
Toggle rspo2rknp_xx_data [36] "reg rspo2rknp_xx_data[156:0]"
Toggle rspo2wd_opc [1] "reg rspo2wd_opc[1:0]"
Toggle reqo2rspo_opc_d [1] "reg reqo2rspo_opc_d[3:0]"
Toggle reqo2rspo_opc_d [3] "reg reqo2rspo_opc_d[3:0]"
Toggle reqo2rspo_status_d [1] "reg reqo2rspo_status_d[1:0]"
Toggle spec_rsp_opc [1] "reg spec_rsp_opc[1:0]"
Toggle spec_rsp_status [1] "reg spec_rsp_status[1:0]"
Toggle rsp_opc [1] "reg rsp_opc[1:0]"
Toggle rsp_errcode "reg rsp_errcode[2:0]"
Toggle rsp_status [1] "reg rsp_status[1:0]"
Toggle rsp_data [0] "reg rsp_data[72:0]"
Toggle first_valid_lane [8:3] "net first_valid_lane[8:0]"
Toggle last_valid_lane [8:3] "net last_valid_lane[8:0]"
Toggle total_flit [8:6] "net total_flit[8:0]"
Toggle flit_cnt [7:6] "reg flit_cnt[7:0]"
Toggle spec_rsp_data [9:2] "net spec_rsp_data[72:0]"
Toggle spec_rsp_data [18:11] "net spec_rsp_data[72:0]"
Toggle spec_rsp_data [27:20] "net spec_rsp_data[72:0]"
Toggle spec_rsp_data [36:29] "net spec_rsp_data[72:0]"
Toggle spec_rsp_data [45:38] "net spec_rsp_data[72:0]"
Toggle spec_rsp_data [54:47] "net spec_rsp_data[72:0]"
Toggle spec_rsp_data [63:56] "net spec_rsp_data[72:0]"
Toggle spec_rsp_data [72:65] "net spec_rsp_data[72:0]"
ANNOTATION_END
CHECKSUM: "2974978327 1227282921"
INSTANCE: tb_top.dut.genblk1.U_WRAP_ADJUST
Toggle rspo2wad_offset_addr [0] "net rspo2wad_offset_addr[7:0]"
Toggle rspo2wad_offset_addr [7:3] "net rspo2wad_offset_addr[7:0]"
Toggle wad2rknp_xx_data [36] "reg wad2rknp_xx_data[156:0]"
ANNOTATION_BEGIN: "rknp_xx2wa_head_d can only be asserted after accepting an
unaligned WRW request. Therefore head_d implies opc==WRW and
wa2reqo_offset_addr!=0. Combinations 0/1/1 and 1/0/1 are unreachable"
Toggle rspo2wad_data [36] "net rspo2wad_data[156:0]"
Toggle rspo2wad_opc [1] "net rspo2wad_opc[1:0]"
ANNOTATION_END
CHECKSUM: "1068788094 1103273780"
INSTANCE: tb_top.dut.genblk2.U_ELY_RSP_DETECT
Toggle rspo2erd_opc [1] "net rspo2erd_opc[3:0]"
Toggle rspo2erd_opc [3] "net rspo2erd_opc[3:0]"
ANNOTATION_BEGIN: "rknp_xx2wa_head_d can only be asserted after accepting an
unaligned WRW request. Therefore head_d implies opc==WRW and
wa2reqo_offset_addr!=0. Combinations 0/1/1 and 1/0/1 are unreachable"
Toggle rspt2erd_opc [1] "net rspt2erd_opc[1:0]"
Toggle rspt2erd_errcode "net rspt2erd_errcode[2:0]"
Toggle rspt2erd_status [1] "net rspt2erd_status[1:0]"
Toggle rspt2erd_data [0] "net rspt2erd_data[72:0]"
Toggle erd2rspo_opc [1] "net erd2rspo_opc[1:0]"
Toggle erd2rspo_errcode "net erd2rspo_errcode[2:0]"
Toggle erd2rspo_status [1] "net erd2rspo_status[1:0]"
Toggle erd2rspo_data [0] "net erd2rspo_data[72:0]"
ANNOTATION_END
CHECKSUM: "4134167130 472136331"
INSTANCE: tb_top.dut.U_ADDR_MAP
Toggle rspo2am_subr [7:3] "net rspo2am_subr[7:0]"
Toggle rspo2am_opc [1] "net rspo2am_opc[3:0]"
Toggle rspo2am_opc [3] "net rspo2am_opc[3:0]"
Toggle am2rreqt_opc [1] "net am2rreqt_opc[1:0]"
Toggle am2wreqt_opc [1] "net am2wreqt_opc[1:0]"
ANNOTATION_BEGIN: "rknp_xx2wa_head_d can only be asserted after accepting an
unaligned WRW request. Therefore head_d implies opc==WRW and
wa2reqo_offset_addr!=0. Combinations 0/1/1 and 1/0/1 are unreachable"
Toggle am2rreqt_araddr [34:32] "net am2rreqt_araddr[39:0]"
Toggle am2rreqt_araddr [39] "net am2rreqt_araddr[39:0]"
Toggle am2rreqt_arlen [7:6] "net am2rreqt_arlen[7:0]"
Toggle am2wreqt_awaddr [34:32] "net am2wreqt_awaddr[39:0]"
Toggle am2wreqt_awaddr [39] "net am2wreqt_awaddr[39:0]"
Toggle am2wreqt_awlen [7:6] "net am2wreqt_awlen[7:0]"
Toggle beat_count [8:6] "net beat_count[8:0]"
Toggle total_flit [7:6] "net total_flit[7:0]"
ANNOTATION_END
CHECKSUM: "3424761348 3180198022"
INSTANCE: tb_top.dut.U_WATCHDOG
Toggle reqo2wd_opc [1] "net reqo2wd_opc[1:0]"
Toggle reqo2wd_timout_table [5] "net reqo2wd_timout_table[79:0]"
Toggle reqo2wd_timout_table [15] "net reqo2wd_timout_table[79:0]"
Toggle reqo2wd_timout_table [25] "net reqo2wd_timout_table[79:0]"
Toggle reqo2wd_timout_table [35] "net reqo2wd_timout_table[79:0]"
Toggle reqo2wd_timout_table [45] "net reqo2wd_timout_table[79:0]"
Toggle reqo2wd_timout_table [55] "net reqo2wd_timout_table[79:0]"
Toggle reqo2wd_timout_table [65] "net reqo2wd_timout_table[79:0]"
Toggle reqo2wd_timout_table [75] "net reqo2wd_timout_table[79:0]"
ANNOTATION_BEGIN: "rknp_xx2wa_head_d can only be asserted after accepting an
unaligned WRW request. Therefore head_d implies opc==WRW and
wa2reqo_offset_addr!=0. Combinations 0/1/1 and 1/0/1 are unreachable"
Toggle reqo2wd_timout_table [1] "net reqo2wd_timout_table[79:0]"
Toggle rspo2wd_opc [1] "net rspo2wd_opc[1:0]"
ANNOTATION_END
CHECKSUM: "1561113057 3296988405"
INSTANCE: tb_top.dut.U_RREQ_TRANS
Toggle am2rreqt_opc [1] "net am2rreqt_opc[1:0]"
ANNOTATION_BEGIN: "rknp_xx2wa_head_d can only be asserted after accepting an
unaligned WRW request. Therefore head_d implies opc==WRW and
wa2reqo_offset_addr!=0. Combinations 0/1/1 and 1/0/1 are unreachable"
Toggle am2rreqt_araddr [34:32] "net am2rreqt_araddr[39:0]"
Toggle am2rreqt_araddr [39] "net am2rreqt_araddr[39:0]"
Toggle am2rreqt_arlen [7:6] "net am2rreqt_arlen[7:0]"
Toggle axi_m_araddr [34:32] "reg axi_m_araddr[39:0]"
Toggle axi_m_araddr [39] "reg axi_m_araddr[39:0]"
Toggle axi_m_arlen [7:6] "reg axi_m_arlen[7:0]"
Toggle axi_m_arsize "reg axi_m_arsize[2:0]"
ANNOTATION_END
CHECKSUM: "2953152187 3209974008"
INSTANCE: tb_top.dut.U_WREQ_TRANS
Toggle am2wreqt_opc [1] "net am2wreqt_opc[1:0]"
ANNOTATION_BEGIN: "rknp_xx2wa_head_d can only be asserted after accepting an
unaligned WRW request. Therefore head_d implies opc==WRW and
wa2reqo_offset_addr!=0. Combinations 0/1/1 and 1/0/1 are unreachable"
Toggle am2wreqt_awaddr [34:32] "net am2wreqt_awaddr[39:0]"
Toggle am2wreqt_awaddr [39] "net am2wreqt_awaddr[39:0]"
Toggle am2wreqt_awlen [7:6] "net am2wreqt_awlen[7:0]"
Toggle axi_m_awaddr [34:32] "reg axi_m_awaddr[39:0]"
Toggle axi_m_awaddr [39] "reg axi_m_awaddr[39:0]"
Toggle axi_m_awlen [7:6] "reg axi_m_awlen[7:0]"
ANNOTATION_END
CHECKSUM: "2990987319 1372533909"
INSTANCE: tb_top.axi_vif
ANNOTATION: "rknp_xx2wa_head_d can only be asserted after accepting an
unaligned WRW request. Therefore head_d implies opc==WRW and
wa2reqo_offset_addr!=0. Combinations 0/1/1 and 1/0/1 are unreachable"
Toggle arsize "logic arsize[2:0]"
