`ifndef TEST_FUNCOV_INCR_LEN_SWEEP_SV
`define TEST_FUNCOV_INCR_LEN_SWEEP_SV

// =============================================================================
// File        : test_funcov_incr_len_sweep.sv
// Description : Runs seq_funcov_incr_len_sweep with a deterministic AXI/RKNP
//               response environment so the test focuses on INCR LEN coverage.
// =============================================================================

class test_funcov_incr_len_sweep extends axi_tniu_base_test;
  `uvm_component_utils(test_funcov_incr_len_sweep)

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  // Keep this directed coverage test deterministic and fast.  The purpose is
  // only to cover OPC_RD/OPC_WR INCR LEN=0..255; OOO/interleave/backpressure/
  // error injection are already separate functional features.
  virtual function void configure_cfg();
    super.configure_cfg();

    cfg.axi_ooo_en              = 1'b0;
    cfg.axi_interleave_en       = 1'b0;
    cfg.axi_force_interleave_en = 1'b0;

    cfg.axi_ready_bp_en         = 1'b0;
    cfg.rsp_ready_bp_en         = 1'b0;

    cfg.axi_min_addr_delay      = 0;
    cfg.axi_max_addr_delay      = 0;
    cfg.axi_min_resp_delay      = 0;
    cfg.axi_max_resp_delay      = 0;
    cfg.axi_min_beat_gap        = 0;
    cfg.axi_max_beat_gap        = 0;

    cfg.axi_rsp_user_random_en  = 1'b0;
    cfg.axi_rsp_user_fixed      = '0;

    cfg.axi_error_rsp_en         = 1'b0;
    cfg.axi_error_resp_random_en = 1'b0;

    cfg.req_min_gap             = 0;
    cfg.req_max_gap             = 0;
    cfg.rsp_ready_low_pct       = 0;

    // 512 requests are generated by the sequence.  Give response draining
    // ample margin without changing watchdog behavior.
    cfg.rsp_drain_timeout       = 2ms;
  endfunction

  task run_testcase();
    seq_funcov_incr_len_sweep seq;

    seq = seq_funcov_incr_len_sweep::type_id::create("seq");

    `uvm_info("TEST_FUNCOV_INCR_LEN",
              "Running directed RD/WR INCR LEN sweep (0..255 each)",
              UVM_LOW)

    start_rknp_sequence(seq);
  endtask

endclass : test_funcov_incr_len_sweep

`endif // TEST_FUNCOV_INCR_LEN_SWEEP_SV
