`ifndef TEST_SAMEAXID_BUF_ERR_ALT_SV
`define TEST_SAMEAXID_BUF_ERR_ALT_SV

// =============================================================================
// File        : test_sameaxid_buf_err_alt.sv
// Feature     : Same-AXID BUFFERABLE/ERROR writes:
//               BUF -> ERR -> BUF -> ERR
// =============================================================================

class test_sameaxid_buf_err_alt extends axi_tniu_base_test;
  `uvm_component_utils(test_sameaxid_buf_err_alt)

  localparam axi_tniu_protocol_pkg::ordkey_t FIXED_ORDERKEY = 8'h55;

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  virtual function void configure_cfg();
    // Keep the environment deterministic.  Request ST_ERR is generated by the
    // sequence itself; AXI-side error injection is deliberately disabled.
    cfg.axi_ooo_en              = 1'b0;
    cfg.axi_interleave_en       = 1'b0;
    cfg.axi_force_interleave_en = 1'b0;

    cfg.axi_ready_bp_en   = 1'b0;
    cfg.rsp_ready_bp_en   = 1'b0;
    cfg.rsp_ready_low_pct = 0;

    cfg.axi_min_addr_delay = 0;
    cfg.axi_max_addr_delay = 0;
    cfg.axi_min_resp_delay = 0;
    cfg.axi_max_resp_delay = 0;
    cfg.axi_min_beat_gap   = 0;
    cfg.axi_max_beat_gap   = 0;

    cfg.axi_error_rsp_en         = 1'b0;
    cfg.axi_error_resp_random_en = 1'b0;
    cfg.axi_slverr_pct           = 0;

    // Stress adjacency; the updated RKNP driver interprets zero as no
    // driver-inserted packet gap when the next item is available.
    cfg.req_min_gap = 0;
    cfg.req_max_gap = 0;

    cfg.rsp_drain_timeout = 200us;
  endfunction

  virtual task run_testcase();
    seq_sameaxid_buf_err_alt seq;
    axi_tniu_protocol_pkg::axi_id_t axid;

    seq = seq_sameaxid_buf_err_alt::type_id::create("seq");
    seq.use_fixed_orderkey = 1'b1;
    seq.fixed_orderkey     = FIXED_ORDERKEY;

    axid = axi_tniu_protocol_pkg::map_ordkey_to_axid(FIXED_ORDERKEY);

    `uvm_info(
      "TEST_SAMEAXID_BUF_ERR_ALT",
      $sformatf("Run fixed OrderKey=0x%0h -> AXID=0x%0h",
                FIXED_ORDERKEY, axid),
      UVM_LOW
    )

    start_rknp_sequence(seq);
  endtask

endclass : test_sameaxid_buf_err_alt

`endif // TEST_SAMEAXID_BUF_ERR_ALT_SV
